# adapted from https://towardsdatascience.com/pre-commit-hooks-you-must-know-ff247f5feb7e
# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-ast
    -   id: check-case-conflict
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: fix-byte-order-marker
    -   id: trailing-whitespace
    -   id: mixed-line-ending
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v0.910
#    hooks:
#    -   id: mypy
#        args: [--ignore-missing-imports]
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.3
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    -   id: black
        args: [-l 79]
    -   id: black-jupyter
        args: [-l 79]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==20.8b1]
#-   repo: https://github.com/tomcatling/black-nb
#    rev: '0.6'
#    hooks:
#    -   id: black-nb
#        args: [-l 79]
-   repo: https://github.com/s-weigand/flake8-nb
    rev: v0.3.1
    hooks:
    -   id: flake8-nb
-   repo: https://github.com/pycqa/pylint
    rev: v2.11.1
    hooks:
    -   id: pylint
