# adapted from https://towardsdatascience.com/pre-commit-hooks-you-must-know-ff247f5feb7e
# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
repos:
-   repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
    -   id: black-jupyter
        args: [-l 79]
